Feature bulk request
Flowpack/Flowpack.ElasticSearch pull request #81
Opened 2019-02-05 17:34 UTC by cwenzelg

Adds a feature to push bulk requests. This is necessary if you want to create index tables based on thousands of entries via a command for example.

2019-06-13 12:16 UTC, DavidSporer commented
In case it helps: we've tried this today and it works like a charm :-)
Speeds up updating a large index (in this case 1.4 million records) by a factor of 30.

2019-10-22 05:43 UTC, daniellienert requested changes

2019-10-22 05:43 UTC, daniellienert commented on Classes/Domain/Model/AbstractType.php
> +    public function request($method, $path = null, array $arguments = [], $content = null, $header = null)
please specify the the type of the `$header` attribute and mention it in the commet

2019-10-22 05:43 UTC, daniellienert commented on Classes/Domain/Model/AbstractType.php
> +    public function bulkRequest(array $arguments = [], $content = null)
Return type missing

2019-10-22 05:43 UTC, daniellienert commented on Classes/Domain/Model/Client.php
> +    public function request($method, $path = null, array $arguments = [], $content = null, $header = null)
If the header is a string, wouldn't be an empty string a better default?

2019-10-22 05:43 UTC, daniellienert commented on Classes/Transfer/RequestService.php
> +        $header = $header ?: 'application/json';
Wouldn't be 'application/json' a better default then?

2019-10-22 05:45 UTC, daniellienert commented
Hey cwenzelg, thanks for the PR and sorry for the late review. 
As I adapted the package for Flow 6.0 in the meantime, this PR needs to be adjusted as well. 
Would you take care?

Cheers,
Daniel

2019-10-22 07:20 UTC, cwenzelg commented
Hi @daniellienert , well this pull request ist really old. even before the return types etc. We are not working with Flow 6.0 so I don't know the changes that need to be done. we use our own branch till now and I would really love a backword merge with an older version so we can use it with the older versions, too. would that be possible. I can push a new commit that takes care about your comments.

2026-09-14 07:53 UTC, closed without merging