BUGFIX: Removed index_name in MultiField-Mapping
Flowpack/Flowpack.ElasticSearch pull request #96
Opened 2022-02-14 15:58 UTC by fdsis

### Problem
Using a mapping with one field `@ElasticSearch\Mapping(type="text", fields={@ElasticSearch\Mapping(index_name="raw", type="keyword")})` results in a wrong mapping configuration. 

### Example based on [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/indices-put-mapping.html#add-multi-fields-existing-field-ex)

How it should look like:
```json
{
  "properties": {
    "city": {
      "type": "text",
      "fields": {
        "raw": {
          "type": "keyword"
        }
      }
    }
  }
}
```
How it does look like:
```json
{
  "properties": {
    "city": {
      "type": "text",
      "fields": {
        "raw": {
          "type": "keyword",
          "index_name": "raw"
        }
      }
    }
  }
}
```

### Solution
This PR contains a simple fix by just not setting the `index_name` property in a field configuration.

### Setup
```
"neos/flow": "7.3.1",
"flowpack/elasticsearch-contentrepositoryadaptor": "~8.0",
"flowpack/elasticsearch": "~5.0",
```

2022-11-11 07:10 UTC, simstern commented
Just wanted to submit a PR with the same fix 👍

2023-01-25 11:57 UTC, kitsunet requested changes
I am not sure this is still sensible, took ages to look at but AFAIK index_name is no longer supported either way, and if then we would need to differentiate between sup fields and the main field I think.

2023-01-25 12:03 UTC, kitsunet commented
Will probably close unless someone can point me to the docs about it within current ES or I am missing something.

2023-01-25 12:10 UTC, simstern commented
@kitsunet I think this is still valid. I'm running ES v7.16. Without this fix, I get an exception. I will try to reconstruct this case and give further explanation.

2023-01-25 15:48 UTC, kitsunet commented
> 

Cool, thank you so much. I would love to see how this happens, I will serach a bit more about the option within current versions.

2023-01-25 15:55 UTC, kitsunet commented
NVM, I am sorry I get it now, that original implementation is a bit hacky I guess^^

2023-01-25 15:57 UTC, kitsunet commented
I would however suggest to fix it like this: https://github.com/Flowpack/Flowpack.ElasticSearch/blob/master/Classes/Annotations/Mapping.php#L137

2023-01-30 07:54 UTC, simstern commented
@kitsunet This PR actually fixes 2 bugs related to multi-fields:

**Bug 1: Field type is always overwritten in "sub-field" of multi-fields**. This is not explained in the problem description above, but fixed on Line 134: https://github.com/Flowpack/Flowpack.ElasticSearch/pull/96/files#diff-defed0b6e36d5a82266dac2d217323f5af70a6183337cfe388730880a446fcbaR134

The full problem description therefore should be as follows.

How it should look like:
```json
{
  "properties": {
    "city": {
      "type": "text",
      "fields": {
        "raw": {
          "type": "keyword"
        }
      }
    }
  }
}
```
How it does look like:
```json
{
  "properties": {
    "city": {
      "type": "text",
      "fields": {
        "raw": {
          "type": "text",
          "index_name": "raw"
        }
      }
    }
  }
}
```
 Both, type and index_name of the sub-field are wrong:
1. `type` of raw field should be "keyword," but is "text"
2. `index_name` should not be present

**Bug 2: index_name is set on "sub-field" of multi-fields**, as explained originally. I agree, it might be better to unset index_name this inside the `getPropertiesArray`.

2023-01-31 14:38 UTC, fdsis commented
As https://github.com/Flowpack/Flowpack.ElasticSearch/pull/109 replaces this PR is there any reason to not close it?

2023-02-10 08:49 UTC, closed without merging